#server:
#  port: 9000
#
#spring:
#  jpa:
#    database: mysql
#    properties.hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
#    hibernate:
#      ddl-auto: create
#    show-sql: true
#    properties:
#      hibernate.format_sql: true
#  datasource:
#    url: jdbc:mysql://localhost:3308/spring?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
#    username: root
#    password: 1234
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    initialization-mode: always
#    platform: oauth2
#
#
#security:
#  oauth2:
#    authorization:
##      check-token-access: isAuthenticated()
#      check-token-access: permitAll()
#
##    client:
##      client-id: volt-android
##      client-secret: volt
##    resource:
##      jwt:
##        key-value: kanghodong
#
